---
- name: 
  lineinfile:
    dest: /etc/pam.d/common-password
    line: "{{ item.line }}"
    insertafter: EOF
  with_items:
    - { line: 'password required pam_unix.so use_authtok md5' }
    - { line: 'password required pam_cracklib.so retry=1 minlen=6 difok=3' }
