---
- name: 
  lineinfile:
    dest: /etc/pam.d/passwd
    line: "{{ item.line }}"
    insertafter: EOF
  with_items:
    - { line: '#%PAM-1.0 (set by ansible)' }
    - { line: 'password required pam_cracklib.so retry=2 minlen=10 difok=6 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1' }
    - { line: 'password required pam_unix.so use_authtok sha512 shadow' }
