---
- name: create clamav log directory
  file:
    path: /var/log/clamav
    state: directory
    mode: 0700
- name: clamav update database daily
  cron:
    name: update clamav database
    user: root
    minute: 0
    hour: 1
    job: freshclam
- name: clamav /home scan cronjob
  cron:
    name: "scan /home"
    user: root
    minute: 0
    hour: 6
    job: find /home -type f -print0 | xargs -0 -P 2 clamscan -i > /var/log/clamav/daily-scan.txt 
